version: 2

models:
  - name: fct_metrics
    columns:
      - name: metric_date
        tests:
          - not_null
      - name: record_count
        tests:
          - not_null

  - name: dim_entities
    columns:
      - name: id
        tests:
          - not_null
          - unique
